version: '3'
services:
  postgres:
    container_name: ${POSTGRES_HOST}
    restart: always
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
  api:
    build: ./backend
    container_name: ${API_HOST}
    restart: always
    expose:
      - ${API_PORT}
    ports:
      # Remove when NGINX is in place
      - ${API_PORT}:${API_PORT}
    depends_on:
      - postgres
    volumes:
      - ./backend:/server
volumes:
  postgres:
