version: '3'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    expose:
      - ${POSTGRES_PORT}
    ports:
      # NOTE: Not suitable for production
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - flow
  server:
    build: ./backend
    container_name: flow-sever
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./backend/app:/app
    networks:
      - flow
networks:
  flow:
volumes:
  postgres:
