DROP SCHEMA aggregate CASCADE;
DROP SCHEMA materialized CASCADE;
DROP SCHEMA public CASCADE;
DROP SCHEMA queue CASCADE;
DROP SCHEMA secret CASCADE;
DROP SCHEMA work CASCADE;
CREATE SCHEMA public; -- exists by default
