package auth

import (
	"context"
	"os"
	"testing"

	apienv "flow/api/env"
	"flow/common/db"
	commonenv "flow/common/env"
)

// Fixtures shadow application tables for this transaction only; no real users
// or invitations are modified. Use a disposable, trust-authenticated Postgres.
func signupTestDB(t *testing.T) (*db.Conn, *db.Tx) {
	t.Helper()
	host := os.Getenv("TEST_POSTGRES_HOST")
	if host == "" {
		t.Skip("set TEST_POSTGRES_HOST to run PostgreSQL integration tests")
	}
	conn, err := db.ConnectPool(context.Background(), &commonenv.Environment{
		PostgresHost: host, PostgresPort: "5432", PostgresUser: "postgres", PostgresDatabase: "postgres",
	})
	if err != nil {
		t.Fatal(err)
	}
	tx, err := conn.Begin()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { tx.Rollback() })
	oldKey := apienv.Global.JwtKey
	apienv.Global.JwtKey = []byte("signup-invite-regression-test-key")
	t.Cleanup(func() { apienv.Global.JwtKey = oldKey })
	_, err = tx.Exec(`
		CREATE TEMP TABLE "user" (
			id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
			email text, secret_id text, first_name text, last_name text,
			join_source text, picture_url text
		) ON COMMIT DROP;
		CREATE TEMP TABLE shared_group_member (
			group_id integer, user_id integer REFERENCES "user"(id),
			status text CHECK (status IN ('pending', 'member')),
			created_at timestamptz NOT NULL DEFAULT NOW(),
			PRIMARY KEY (group_id, user_id)
		) ON COMMIT DROP;
		INSERT INTO "user" (id, email) VALUES
			(1, 'Recipient@Example.Test'), (2, 'recipient@example.test'),
			(3, 'other@example.test');
		INSERT INTO shared_group_member (group_id, user_id, status, created_at) VALUES
			(9, 1, 'pending', '2026-09-01'), (9, 2, 'pending', '2026-09-02'),
			(10, 1, 'member', '2026-09-01'), (11, 3, 'pending', '2026-09-01');
	`)
	if err != nil {
		t.Fatal(err)
	}
	return conn, tx
}

func TestInsertUserInheritsPendingInvites(t *testing.T) {
	for _, source := range []string{"email", "google"} {
		t.Run(source, func(t *testing.T) {
			conn, tx := signupTestDB(t)
			email := "RECIPIENT@example.test"
			response, err := InsertUser(tx, &userInfo{Email: &email, JoinSource: source})
			if err != nil {
				t.Fatal(err)
			}
			var count, groupID int
			var status, createdAt string
			if err := tx.QueryRow(`SELECT count(*) FROM shared_group_member WHERE user_id = $1`, response.UserId).Scan(&count); err != nil {
				t.Fatal(err)
			}
			if count != 1 {
				t.Fatalf("want one deduplicated pending invite, got %d memberships", count)
			}
			if err := tx.QueryRow(`SELECT group_id, status, created_at::date::text FROM shared_group_member WHERE user_id = $1`, response.UserId).Scan(&groupID, &status, &createdAt); err != nil {
				t.Fatal(err)
			}
			if groupID != 9 || status != "pending" || createdAt != "2026-09-01" {
				t.Fatalf("unexpected inherited invite: group=%d status=%s created=%s", groupID, status, createdAt)
			}
			if !response.IsNew || response.Token == "" {
				t.Fatal("signup did not issue an authenticated new account")
			}
			// The invitation endpoint must wait until signup commits, even when
			// it receives a differently cased version of the same address.
			other, err := conn.Begin()
			if err != nil {
				t.Fatal(err)
			}
			defer other.Rollback()
			var acquired bool
			if err := other.QueryRow(`SELECT pg_try_advisory_xact_lock(hashtextextended('recipient@example.test', 0))`).Scan(&acquired); err != nil {
				t.Fatal(err)
			}
			if acquired {
				t.Fatal("signup did not hold the invitation endpoint's email lock")
			}
		})
	}
}

func TestInsertUserWithoutMatchingInvites(t *testing.T) {
	uninvited, empty := "new@example.test", ""
	for _, email := range []*string{&uninvited, &empty, nil} {
		t.Run("email", func(t *testing.T) {
			_, tx := signupTestDB(t)
			response, err := InsertUser(tx, &userInfo{Email: email})
			if err != nil {
				t.Fatal(err)
			}
			var count int
			if err := tx.QueryRow(`SELECT count(*) FROM shared_group_member WHERE user_id = $1`, response.UserId).Scan(&count); err != nil {
				t.Fatal(err)
			}
			if count != 0 {
				t.Fatalf("uninvited account inherited %d memberships", count)
			}
		})
	}
}

func TestInsertUserInheritsAtMostTwentyInvites(t *testing.T) {
	_, tx := signupTestDB(t)
	// Each source account is under its quota, but their combined invitations
	// exceed it. Signup must succeed with the oldest 20 distinct invitations.
	_, err := tx.Exec(`
		DELETE FROM shared_group_member;
		INSERT INTO shared_group_member (group_id, user_id, status, created_at)
		SELECT n, CASE WHEN n <= 15 THEN 1 ELSE 2 END, 'pending', '2026-09-01'
		FROM generate_series(1, 30) n;
	`)
	if err != nil {
		t.Fatal(err)
	}
	email := "recipient@example.test"
	response, err := InsertUser(tx, &userInfo{Email: &email})
	if err != nil {
		t.Fatal(err)
	}
	var count, lastGroup int
	if err := tx.QueryRow(`SELECT count(*), max(group_id) FROM shared_group_member WHERE user_id = $1`, response.UserId).Scan(&count, &lastGroup); err != nil {
		t.Fatal(err)
	}
	if count != 20 || lastGroup != 20 {
		t.Fatalf("want oldest 20 invites, got count=%d last_group=%d", count, lastGroup)
	}
}
